services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
before_install:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t ${IMAGE}:${COMMIT} .
# prepare trivy
- export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest"
  | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
- wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
- tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
script:
# execute trify vulnerability scan
- "./trivy --exit-code 0 --severity HIGH --no-progress ${IMAGE}:${COMMIT}"
- "./trivy --exit-code 1 --severity CRITICAL --no-progress ${IMAGE}:${COMMIT}"
# sign image
- docker trust sign ${IMAGE}:${COMMIT}
after_success:
- export TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag ${IMAGE}:${COMMIT} ${IMAGE}:${TAG}
- docker push ${IMAGE}:${TAG}
cache:
  directories:
  - "$HOME/.cache/trivy"
